### ISSUE TITLE
Compile errors in windows

### ISSUE THREAD

**Issue by cdwijs** [Pinguinsan/QSerialTerminal#2]
Hi,
I have tried to compile the source in Qt 5.9.1 using mingw53_32 on windows 7, but I get errors during compiling. I was able to fix some basic errors (see the patch), but then I got a lot of errors about the serial port handling, and I was unable to solve those. 

I'm unable to atach files for some reason, therefore i've pased the patch and the compile output below:
patch:
 QSerialTerminal.pro | 6 +-----
 src/Main.cpp        | 4 ++++
 src/MainWindow.cpp  | 6 +++++-
 3 files changed, 10 insertions(+), 6 deletions(-)

diff --git a/QSerialTerminal.pro b/QSerialTerminal.pro
index 13e3e76..f092f89 100644
--- a/QSerialTerminal.pro
+++ b/QSerialTerminal.pro
@@ -33,8 +33,6 @@ src/ApplicationSettings.cpp \
 src/ApplicationSettingsLoader.cpp \
 src/MainWindow.cpp \
 src/ApplicationIcons.cpp \
-src/ApplicationStrings.cpp \
-src/CustomAction.cpp \
 src/QSerialTerminalLineEdit.cpp \
 src/ApplicationUtilities.cpp \
 src/AboutApplicationWidget.cpp
@@ -46,7 +44,6 @@ HEADERS += \
     src/MainWindow.h \
     src/ApplicationIcons.h \
     src/ApplicationStrings.h \
-    src/CustomAction.h \
     src/QSerialTerminalLineEdit.h \
     src/ApplicationUtilities.h \
     src/SerialPort.h \
@@ -59,7 +56,6 @@ FORMS += \
         forms/AboutApplicationWidget.ui
 
 RESOURCES += \
-    resources/icons.qrc \
-    resources/translations.qrc
+    resources/icons.qrc
 
 
diff --git a/src/Main.cpp b/src/Main.cpp
index 10b7abd..84ea236 100644
--- a/src/Main.cpp
+++ b/src/Main.cpp
@@ -77,7 +77,11 @@ int main(int argc, char *argv[])
 void exitApplication(const std::string &why)
 {
     LOG_INFO() << "Exiting application for reason: \"" << QString::fromStdString(why) << "\"";
+#if defined(_WIN32)
+    //interruptHandler(0);
+#else
     interruptHandler(SIGQUIT);
+#endif
 }
 
 void interruptHandler(int signalNumber)
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index aed6f53..ab965b4 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -452,10 +452,14 @@ void MainWindow::setupAdditionalUiComponents()
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD38400));
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD57600));
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD115200));
+#if defined(_WIN32) //windows: 'BAUD230400',BAUD460800 and BAUD2000000 is not a member of 'CppSerialPort::BaudRate'                                                                                               ^
+#else
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD230400));
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD460800));
-    this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD1000000));
     this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD2000000));
+#endif
+    this->addNewSerialPortInfoItem(SerialPortItemType::BAUD_RATE, CppSerialPort::SerialPort::baudRateToString(CppSerialPort::BaudRate::BAUD1000000));
+
 
     for (auto &it : CppSerialPort::SerialPort::availableSerialPorts()) {
         this->addNewSerialPortInfoItem(SerialPortItemType::PORT_NAME, it);

compile output:
11:36:08: Running steps for project QSerialTerminal...
11:36:08: Configuration unchanged, skipping qmake step.
11:36:08: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" 
C:\Qt\5.9.1\mingw53_32\bin\qmake.exe -o Makefile ..\QSerialTerminal\QSerialTerminal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'Z:/git/build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug'
g++ -fno-keep-inline-dllexport -pipe -g -std=gnu++11 -Wextra -Wall -W -dM -E -o debug\moc_predefs.h C:\Qt\5.9.1\mingw53_32\mkspecs\features\data\dummy.cpp
C:\Qt\5.9.1\mingw53_32\bin\moc.exe -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN --include debug/moc_predefs.h -IC:/Qt/5.9.1/mingw53_32/mkspecs/win32-g++ -IZ:/git/QSerialTerminal -IZ:/git/QSerialTerminal/src -IC:/Qt/5.9.1/mingw53_32/include -IC:/Qt/5.9.1/mingw53_32/include/QtWidgets -IC:/Qt/5.9.1/mingw53_32/include/QtGui -IC:/Qt/5.9.1/mingw53_32/include/QtANGLE -IC:/Qt/5.9.1/mingw53_32/include/QtCore -I. -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward ..\QSerialTerminal\src\ApplicationSettingsLoader.h -o debug\moc_ApplicationSettingsLoader.cpp
g++ -c -fno-keep-inline-dllexport -pipe -g -std=gnu++11 -Wextra -Wall -W -fexceptions -mthreads -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I..\QSerialTerminal -I. -I..\QSerialTerminal\src -IC:\Qt\5.9.1\mingw53_32\include -IC:\Qt\5.9.1\mingw53_32\include\QtWidgets -IC:\Qt\5.9.1\mingw53_32\include\QtGui -IC:\Qt\5.9.1\mingw53_32\include\QtANGLE -IC:\Qt\5.9.1\mingw53_32\include\QtCore -Idebug -I. -IC:\Qt\5.9.1\mingw53_32\mkspecs\win32-g++  -o debug\moc_ApplicationSettingsLoader.o debug\moc_ApplicationSettingsLoader.cpp
C:\Qt\5.9.1\mingw53_32\bin\moc.exe -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN --include debug/moc_predefs.h -IC:/Qt/5.9.1/mingw53_32/mkspecs/win32-g++ -IZ:/git/QSerialTerminal -IZ:/git/QSerialTerminal/src -IC:/Qt/5.9.1/mingw53_32/include -IC:/Qt/5.9.1/mingw53_32/include/QtWidgets -IC:/Qt/5.9.1/mingw53_32/include/QtGui -IC:/Qt/5.9.1/mingw53_32/include/QtANGLE -IC:/Qt/5.9.1/mingw53_32/include/QtCore -I. -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward ..\QSerialTerminal\src\MainWindow.h -o debug\moc_MainWindow.cpp
g++ -c -fno-keep-inline-dllexport -pipe -g -std=gnu++11 -Wextra -Wall -W -fexceptions -mthreads -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I..\QSerialTerminal -I. -I..\QSerialTerminal\src -IC:\Qt\5.9.1\mingw53_32\include -IC:\Qt\5.9.1\mingw53_32\include\QtWidgets -IC:\Qt\5.9.1\mingw53_32\include\QtGui -IC:\Qt\5.9.1\mingw53_32\include\QtANGLE -IC:\Qt\5.9.1\mingw53_32\include\QtCore -Idebug -I. -IC:\Qt\5.9.1\mingw53_32\mkspecs\win32-g++  -o debug\moc_MainWindow.o debug\moc_MainWindow.cpp
In file included from debug\moc_MainWindow.cpp:9:0:
Z:/git/QSerialTerminal/src/MainWindow.h: In destructor 'virtual MainWindow::~MainWindow()':
Z:/git/QSerialTerminal/src/MainWindow.h:47:43: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     ~MainWindow() override { delete this->m_ui; }
                                           ^
Z:/git/QSerialTerminal/src/MainWindow.h:47:43: warning: invalid use of incomplete type 'class Ui::MainWindow'
Z:/git/QSerialTerminal/src/MainWindow.h:30:11: note: forward declaration of 'class Ui::MainWindow'
     class MainWindow;
           ^
Z:/git/QSerialTerminal/src/MainWindow.h:47:43: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     ~MainWindow() override { delete this->m_ui; }
                                           ^
C:\Qt\5.9.1\mingw53_32\bin\moc.exe -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN --include debug/moc_predefs.h -IC:/Qt/5.9.1/mingw53_32/mkspecs/win32-g++ -IZ:/git/QSerialTerminal -IZ:/git/QSerialTerminal/src -IC:/Qt/5.9.1/mingw53_32/include -IC:/Qt/5.9.1/mingw53_32/include/QtWidgets -IC:/Qt/5.9.1/mingw53_32/include/QtGui -IC:/Qt/5.9.1/mingw53_32/include/QtANGLE -IC:/Qt/5.9.1/mingw53_32/include/QtCore -I. -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward ..\QSerialTerminal\src\QSerialTerminalLineEdit.h -o debug\moc_QSerialTerminalLineEdit.cpp
g++ -c -fno-keep-inline-dllexport -pipe -g -std=gnu++11 -Wextra -Wall -W -fexceptions -mthreads -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I..\QSerialTerminal -I. -I..\QSerialTerminal\src -IC:\Qt\5.9.1\mingw53_32\include -IC:\Qt\5.9.1\mingw53_32\include\QtWidgets -IC:\Qt\5.9.1\mingw53_32\include\QtGui -IC:\Qt\5.9.1\mingw53_32\include\QtANGLE -IC:\Qt\5.9.1\mingw53_32\include\QtCore -Idebug -I. -IC:\Qt\5.9.1\mingw53_32\mkspecs\win32-g++  -o debug\moc_QSerialTerminalLineEdit.o debug\moc_QSerialTerminalLineEdit.cpp
C:\Qt\5.9.1\mingw53_32\bin\moc.exe -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN --include debug/moc_predefs.h -IC:/Qt/5.9.1/mingw53_32/mkspecs/win32-g++ -IZ:/git/QSerialTerminal -IZ:/git/QSerialTerminal/src -IC:/Qt/5.9.1/mingw53_32/include -IC:/Qt/5.9.1/mingw53_32/include/QtWidgets -IC:/Qt/5.9.1/mingw53_32/include/QtGui -IC:/Qt/5.9.1/mingw53_32/include/QtANGLE -IC:/Qt/5.9.1/mingw53_32/include/QtCore -I. -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward ..\QSerialTerminal\src\AboutApplicationWidget.h -o debug\moc_AboutApplicationWidget.cpp
g++ -c -fno-keep-inline-dllexport -pipe -g -std=gnu++11 -Wextra -Wall -W -fexceptions -mthreads -DUNICODE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I..\QSerialTerminal -I. -I..\QSerialTerminal\src -IC:\Qt\5.9.1\mingw53_32\include -IC:\Qt\5.9.1\mingw53_32\include\QtWidgets -IC:\Qt\5.9.1\mingw53_32\include\QtGui -IC:\Qt\5.9.1\mingw53_32\include\QtANGLE -IC:\Qt\5.9.1\mingw53_32\include\QtCore -Idebug -I. -IC:\Qt\5.9.1\mingw53_32\mkspecs\win32-g++  -o debug\moc_AboutApplicationWidget.o debug\moc_AboutApplicationWidget.cpp
g++ -Wl,-subsystem,windows -mthreads -o debug\QSerialTerminal.exe object_script.QSerialTerminal.Debug  -lmingw32 -LC:\Qt\5.9.1\mingw53_32\lib C:\Qt\5.9.1\mingw53_32\lib\libqtmaind.a -LC:\utils\my_sql\my_sql\lib -LC:\utils\postgresql\pgsql\lib -lshell32 C:\Qt\5.9.1\mingw53_32\lib\libQt5Widgetsd.a C:\Qt\5.9.1\mingw53_32\lib\libQt5Guid.a C:\Qt\5.9.1\mingw53_32\lib\libQt5Cored.a 
./debug\MainWindow.o: In function `ZN10MainWindowC2EP7QWidget':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:53: undefined reference to `CppSerialPort::SerialPort::availableSerialPorts[abi:cxx11]()'
./debug\MainWindow.o: In function `ZN10MainWindow17autoSetLineEndingEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:137: undefined reference to `CppSerialPort::IByteStream::setLineEnding(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./debug\MainWindow.o: In function `ZN10MainWindow28checkDisconnectedSerialPortsEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:171: undefined reference to `CppSerialPort::SerialPort::availableSerialPorts[abi:cxx11]()'
./debug\MainWindow.o: In function `ZN10MainWindow24addNewSerialPortInfoItemENS_18SerialPortItemTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:204: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:211: undefined reference to `CppSerialPort::SerialPort::parityToString[abi:cxx11](CppSerialPort::Parity)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:218: undefined reference to `CppSerialPort::SerialPort::dataBitsToString[abi:cxx11](CppSerialPort::DataBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:225: undefined reference to `CppSerialPort::SerialPort::stopBitsToString[abi:cxx11](CppSerialPort::StopBits)'
./debug\MainWindow.o: In function `ZN10MainWindow18checkSerialReceiveB5cxx11Ev':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:334: undefined reference to `CppSerialPort::IByteStream::setLineEnding(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./debug\MainWindow.o: In function `ZN10MainWindow27setupAdditionalUiComponentsEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:435: undefined reference to `CppSerialPort::SerialPort::dataBitsToString[abi:cxx11](CppSerialPort::DataBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:436: undefined reference to `CppSerialPort::SerialPort::dataBitsToString[abi:cxx11](CppSerialPort::DataBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:437: undefined reference to `CppSerialPort::SerialPort::dataBitsToString[abi:cxx11](CppSerialPort::DataBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:438: undefined reference to `CppSerialPort::SerialPort::dataBitsToString[abi:cxx11](CppSerialPort::DataBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:440: undefined reference to `CppSerialPort::SerialPort::stopBitsToString[abi:cxx11](CppSerialPort::StopBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:441: undefined reference to `CppSerialPort::SerialPort::stopBitsToString[abi:cxx11](CppSerialPort::StopBits)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:443: undefined reference to `CppSerialPort::SerialPort::parityToString[abi:cxx11](CppSerialPort::Parity)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:444: undefined reference to `CppSerialPort::SerialPort::parityToString[abi:cxx11](CppSerialPort::Parity)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:445: undefined reference to `CppSerialPort::SerialPort::parityToString[abi:cxx11](CppSerialPort::Parity)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:447: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:448: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:449: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:450: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:451: undefined reference to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)'
./debug\MainWindow.o:Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:452: more undefined references to `CppSerialPort::SerialPort::baudRateToString[abi:cxx11](CppSerialPort::BaudRate)' follow
./debug\MainWindow.o: In function `ZN10MainWindow27setupAdditionalUiComponentsEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:464: undefined reference to `CppSerialPort::SerialPort::availableSerialPorts[abi:cxx11]()'
./debug\MainWindow.o: In function `ZN10MainWindow26onActionLineEndingsCheckedEb':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:544: undefined reference to `CppSerialPort::IByteStream::setLineEnding(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./debug\MainWindow.o: In function `ZN10MainWindow24onActionConnectTriggeredEb':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:615: undefined reference to `CppSerialPort::SerialPort::parseBaudRateFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:616: undefined reference to `CppSerialPort::SerialPort::parseParityFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:617: undefined reference to `CppSerialPort::SerialPort::parseStopBitsFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:618: undefined reference to `CppSerialPort::SerialPort::parseDataBitsFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:621: undefined reference to `CppSerialPort::SerialPort::baudRate() const'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:622: undefined reference to `CppSerialPort::SerialPort::parity() const'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:623: undefined reference to `CppSerialPort::SerialPort::stopBits() const'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:624: undefined reference to `CppSerialPort::SerialPort::dataBits() const'
./debug\MainWindow.o: In function `ZN10MainWindow14openSerialPortEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:679: undefined reference to `CppSerialPort::IByteStream::setReadTimeout(int)'
./debug\MainWindow.o: In function `ZN10MainWindow18beginCommunicationEv':
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:727: undefined reference to `CppSerialPort::SerialPort::parseBaudRateFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:728: undefined reference to `CppSerialPort::SerialPort::parseParityFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:729: undefined reference to `CppSerialPort::SerialPort::parseStopBitsFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Z:\git\build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug/../QSerialTerminal/src/MainWindow.cpp:730: undefined reference to `CppSerialPort::SerialPort::parseDataBitsFromRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./debug\MainWindow.o: In function `ZN9__gnu_cxx13new_allocatorIN13CppSerialPort10SerialPortEE9constructIS2_JRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS1_8BaudRateERNS1_8DataBitsERNS1_8StopBitsERNS1_6ParityEEEEvPT_DpOT0_':
C:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/ext/new_allocator.h:120: undefined reference to `CppSerialPort::SerialPort::SerialPort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CppSerialPort::BaudRate, CppSerialPort::DataBits, CppSerialPort::StopBits, CppSerialPort::Parity)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [debug\QSerialTerminal.exe] Error 1
mingw32-make: *** [debug] Error 2

Makefile.Debug:104: recipe for target 'debug\QSerialTerminal.exe' failed
mingw32-make[1]: Leaving directory 'Z:/git/build-QSerialTerminal-Desktop_Qt_5_9_1_MinGW_32bit-Debug'
Makefile:36: recipe for target 'debug' failed
11:36:42: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project QSerialTerminal (kit: Desktop Qt 5.9.1 MinGW 32bit)
When executing step "Make"
11:36:42: Elapsed time: 00:34.

**Comment by tlewiscpp** [comment]
Sorry about that. I did a huge refactor of the application, and it should compile cleanly on Windows now. Can you give it another shot?

**Comment by cdwijs** [comment]
I have tried it, there was a small error in the .pro file. I have created a pull request with the fix, and with a file detailing the development process on Windows.

Thanks for creating the program.

**Comment by tlewiscpp** [comment]
Thanks for the fixes and documentation!

**Comment by cdwijs** [comment]
Here's the resulting windows binary.
[release.zip](https://github.com/tlewiscpp/QSerialTerminal/files/1595013/release.zip)
